name: CryptoCraft
main: main.Main
version: 1.0
api-version: 1.18
author: UnluckyGermi

commands:
  bal:
    description: See your current balance.
    usage: /bal
  cbal:
    description: See your Crypto Coins and values.
    usage: /cbal
  crypto:
    description: Admin command - Manage the CryptoCraft economy!
    usage: /crypto <Command>
  coin:
    description: Coin commands.
    usage: /coin <Command>